# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dccb778dc2fc7f619a3f1e58e5cf21800d28a47ddf3d77db214dd8bb6a3307fc6efc872c0f0315714525fcd926e5b3dac85eb4cbf5c7cf885b24d6f638f0cb5d
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

test:
  secret_key_base: e1a18930414e66f9d21f46524b3ab82f89b28afbbfd532e028911e968d31e27d25d3b2fd0edd0b49528e2f90a40b1a60c7e15a6641c47f5d352f65c7450fc6ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
